<?php

$title = 'Privacy Policy';
$date = 'Last updated: july 27, 2023';

$text_intro1 = 'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.';
$text_intro2= 'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank">Free Privacy Policy Generator</a>.';

$interpretation_definition = 'Interpretation and Definitions';
$interpretation = 'Interpretation';
$interpretation_text = 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.';
$definition = 'Definitions';
$definition_text = 'For the purposes of this Privacy Policy:';
$def_account = '<strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.';
$def_affiliate = '<strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.';
$def_company = '<strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to CodeLiftoff.';
$def_cookies = '<strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.';
$def_country = '<strong>Country</strong> refers to:  Italy';
$def_device = '<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.';
$def_personal = '<strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.';
$def_service = '<strong>Service</strong> refers to the Website.';
$def_provider = '<strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.';
$def_data = '<strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).';
$def_website = '<strong>Website</strong> refers to CodeLiftoff, accessible from <a href="www.codelifotff.com" rel="external nofollow noopener" target="_blank">www.codelifotff.com</a>';
$def_you = '<strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.';

$collecting = 'Collecting and Using Your Personal Data';
$types_of_data ='Types of Data Collected';
$personal_usage_data = 'Personal Data';
$personal_text = 'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:';
$personal_email = 'Email address';
$personal_name = 'First name and last name';
$personal_number = 'Phone number';
$personal_data = 'Usage Data';

$usage_data = 'Usage Data';
$usage_data_text1 = 'Usage Data is collected automatically when using the Service.';
$usage_data_text2 = 'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.';
$usage_data_text3 = 'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.';
$usage_data_text4 = 'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.';

$tracking = 'Tracking Technologies and Cookies';
$tracking_text1 = 'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:';
$tracking_cookies = '<strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.';
$tracking_web_beacons = '<strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).';
$tracking_text2 = 'Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" target="_blank">Free Privacy Policy website</a> article.';
$tracking_text3 = 'We use both Session and Persistent Cookies for the purposes set out below:';
$tracking_essential = '<strong>Necessary / Essential Cookies</strong>';
$tracking_session = 'Type: Session Cookies';
$tracking_us = 'Administered by: Us';
$tracking_purpose1 = 'Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.';
$tracking_policy = '<strong>Cookies Policy / Notice Acceptance Cookies</strong>';
$tracking_persistent = 'Type: Persistent Cookies';
$tracking_purpose2 = 'Purpose: These Cookies identify if users have accepted the use of cookies on the Website.';
$tracking_functionality = '<strong>Functionality Cookies</strong>';
$tracking_purpose3 = 'Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.';
$tracking_text4 = 'For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.';

$use_personal_data = 'Use of Your Personal Data';
$use_personal_data_text1 = 'The Company may use Personal Data for the following purposes:';
$use_maintain = '<strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.';
$use_account = '<strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.';
$use_performance = '<strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.';
$use_contact = '<strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.';
$use_provide = '<strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.';
$use_request = '<strong>To manage Your requests:</strong> To attend and manage Your requests to Us.';
$use_business = '<strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.';
$use_other = '<strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.';
$use_personal_data_text2 = 'We may share Your personal information in the following situations:';
$share_service = '<strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.';
$share_transfers = '<strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.';
$share_affiliates = '<strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.';
$share_partners = '<strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.';
$share_users = '<strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.';
$share_consent = '<strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.';

$retention = 'Retention of Your Personal Data';
$retention_text1 = 'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.';
$retention_text2 = 'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.';
$transfer = 'Transfer of Your Personal Data';
$transfer_text1 = 'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.';
$transfer_text2 = 'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.';
$transfer_text3 = 'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.';
$delete = 'Delete Your Personal Data';
$delete_text1 = 'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.';
$delete_text2 = 'Our Service may give You the ability to delete certain information about You from within the Service.';
$delete_text3 = 'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.';
$delete_text4 = 'Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.';

$disclosure = 'Disclosure of Your Personal Data';
$transaction = 'Business Transactions';
$transaction_text = 'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.';
$law = 'Law enforcement';
$law_text = 'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).';
$other_requirement = 'Other legal requirements';
$other_requirement_text = 'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:';
$legal_obligation = 'Comply with a legal obligation';
$legal_rights = 'Protect and defend the rights or property of the Company';
$legal_wrongdoings = 'Prevent or investigate possible wrongdoing in connection with the Service';
$legal_personal = 'Protect the personal safety of Users of the Service or the public';
$legal_liability = 'Protect against legal liability';
$security = 'Security of Your Personal Data';
$security_text = 'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.';

$children = 'Children\'s Privacy';
$children_text1 = 'Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.';
$children_text2 = 'If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent\'s consent before We collect and use that information.';

$linkweb = 'Links to Other Websites';
$linkweb_text1 = 'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit.';
$linkweb_text2 = 'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.';

$changes = 'Changes to this Privacy Policy';
$changes_text1 = 'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.';
$changes_text2 = 'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.';
$changes_text3 = 'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.';

$contact = 'Contact Us';
$contact_text = 'If you have any questions about this Privacy Policy, You can contact us:';
$contact_email = 'By email: codeliftoffteam@gmail.com';
$contact_website = 'By visiting this page on our website: <a href="www.codeliftoff.com/pages/privacy.php" rel="external nofollow noopener" target="_blank">www.codeliftoff.com/pages/privacy.php</a>';


$cookies = 'Cookies Policy';

$cookies_text1 = 'This Cookies Policy explains what Cookies are and how We use them. You should read this policy so You can understand what type of cookies We use, or the information We collect using Cookies and how that information is used. This Cookies Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/free-cookies-policy-generator/" target="_blank">Free Cookies Policy Generator</a>.';
$cookies_text2 = 'Cookies do not typically contain any information that personally identifies a user, but personal information that we store about You may be linked to the information stored in and obtained from Cookies. For further information on how We use, store and keep your personal data secure, see our Privacy Policy.';
$cookies_text3 = 'We do not store sensitive personal information, such as mailing addresses, account passwords, etc. in the Cookies We use.';

$cookies_definitions = 'For the purposes of this Cookies Policy:';

$use_cookies = 'The use of the Cookies';
$type_cookies = 'Type of Cookies We Use';
$type_cookies_text1 = 'Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.';
$type_cookies_text2 = 'We use both session and persistent Cookies for the purposes set out below:';

$cookies_choices = 'Your Choices Regarding Cookies';
$cookies_choices_text1 = 'If You prefer to avoid the use of Cookies on the Website, first You must disable the use of Cookies in your browser and then delete the Cookies saved in your browser associated with this website. You may use this option for preventing the use of Cookies at any time.';
$cookies_choices_text2 = 'If You do not accept Our Cookies, You may experience some inconvenience in your use of the Website and some features may not function properly.';
$cookies_choices_text3 = 'If You\'d like to delete Cookies or instruct your web browser to delete or refuse Cookies, please visit the help pages of your web browser.';
$cookies_chrome = 'For the Chrome web browser, please visit this page from Google: <a href="https://support.google.com/accounts/answer/32050" rel="external nofollow noopener" target="_blank">https://support.google.com/accounts/answer/32050</a>';
$cookies_internet = 'For the Internet Explorer web browser, please visit this page from Microsoft: <a href="http://support.microsoft.com/kb/278835" rel="external nofollow noopener" target="_blank">http://support.microsoft.com/kb/278835</a>';
$cookies_firefox = 'For the Firefox web browser, please visit this page from Mozilla: <a href="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored" rel="external nofollow noopener" target="_blank">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</a>';
$cookies_safari = 'For the Safari web browser, please visit this page from Apple: <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" rel="external nofollow noopener" target="_blank" >phttps://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac</a>';
$cookies_choices_text4 = 'For any other web browser, please visit your web browser\'s official web pages.';

$cookies_info = 'More Information about Cookies';
$cookies_info_text = 'You can learn more about cookies: <a href="https://www.freeprivacypolicy.com/blog/cookies/" target="_blank">Cookies: What Do They Do?</a>.';
$cookies_contact = 'If you have any questions about this Cookies Policy, You can contact us:';

?>